--- #YAML:1.0
name:               Archive-BagIt
version:            0.01
abstract:           An interface to make and verify bags according to the BagIt standard
author:
    - Robert Schmidt <rjeschmi@gmail.com>
license:            cc0
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
