---
abstract: 'An interface to make and verify bags according to the BagIt standard'
author:
  - 'Robert Schmidt, <rjeschmi at gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Archive-BagIt
no_index:
  directory:
    - inc
    - t
requires:
  Digest::MD5: 0
  File::Find: 0
  Moose: 0
  MooseX::App::Cmd: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02_4
