---
abstract: 'An interface to make and verify bags according to the BagIt standard'
author:
  - 'Rob Schmidt <rjeschmi@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Archive-BagIt
requires:
  Digest::MD5: '0'
  File::Find: '0'
  Moose: '0'
  MooseX::App::Cmd: '0'
version: '0.043'
